name: Pinche CHANGO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03364b'
    - '#4c7f94'
    - '#ebebeb'
    - '#ab184f'
    - '#d94277'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
